services:
  furrfree-telegram-bot:
    container_name: furrfree-tg
    image: ghcr.io/furrfree/telegram-bot:latest

    env_file: .env
    volumes:
      - ./database.db:/app/database.db
    restart: unless-stopped
